# Generated by Django 3.0.3 on 2020-03-26 10:12

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Camera',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.DecimalField(decimal_places=8, max_digits=10, validators=[django.core.validators.MinValueValidator(-90.0), django.core.validators.MaxValueValidator(90.0)], verbose_name='latitude (degrees)')),
                ('longitude', models.DecimalField(decimal_places=8, max_digits=11, validators=[django.core.validators.MinValueValidator(-180.0), django.core.validators.MaxValueValidator(180.0)], verbose_name='longitude (degrees)')),
                ('start_time', models.DateTimeField(blank=True, null=True, verbose_name='start time')),
                ('end_time', models.DateTimeField(blank=True, null=True, verbose_name='end time')),
            ],
        ),
        migrations.CreateModel(
            name='Clip',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('video_format', models.CharField(max_length=5, verbose_name='format')),
                ('start_time', models.DateTimeField(verbose_name='start time')),
                ('end_time', models.DateTimeField(verbose_name='end time')),
            ],
        ),
        migrations.CreateModel(
            name='Filter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('latitude', models.DecimalField(blank=True, decimal_places=8, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(-90.0), django.core.validators.MaxValueValidator(90.0)], verbose_name='latitude (degrees)')),
                ('longitude', models.DecimalField(blank=True, decimal_places=8, max_digits=11, null=True, validators=[django.core.validators.MinValueValidator(-180.0), django.core.validators.MaxValueValidator(180.0)], verbose_name='longitude (degrees)')),
                ('radius', models.PositiveIntegerField(blank=True, null=True, verbose_name='Radius (m)')),
                ('start_time', models.DateTimeField(blank=True, null=True, verbose_name='start time')),
                ('end_time', models.DateTimeField(blank=True, null=True, verbose_name='end time')),
            ],
        ),
        migrations.CreateModel(
            name='Folder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', models.CharField(blank=True, max_length=200, null=True)),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Object',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='ObjectClass',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_class', models.CharField(max_length=100, verbose_name='class')),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='created')),
                ('last_updated', models.DateTimeField(auto_now=True, verbose_name='last updated')),
                ('folders', models.ManyToManyField(to='backend.Folder')),
            ],
        ),
        migrations.CreateModel(
            name='ObjectDetection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sample_rate', models.FloatField(validators=[django.core.validators.MinValueValidator(0.0)], verbose_name='sample rate (s)')),
                ('start_time', models.DateTimeField(verbose_name='start time')),
                ('end_time', models.DateTimeField(verbose_name='end time')),
                ('camera', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.Camera')),
            ],
        ),
        migrations.AddConstraint(
            model_name='objectclass',
            constraint=models.UniqueConstraint(fields=('object_class',), name='class constraint'),
        ),
        migrations.AddField(
            model_name='object',
            name='object_class',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='backend.ObjectClass'),
        ),
        migrations.AddField(
            model_name='object',
            name='object_detection',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.ObjectDetection'),
        ),
        migrations.AddField(
            model_name='folder',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='backend.Folder'),
        ),
        migrations.AddField(
            model_name='filter',
            name='cameras',
            field=models.ManyToManyField(to='backend.Camera'),
        ),
        migrations.AddField(
            model_name='filter',
            name='classes',
            field=models.ManyToManyField(to='backend.ObjectClass'),
        ),
        migrations.AddField(
            model_name='filter',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.Project'),
        ),
        migrations.AddField(
            model_name='clip',
            name='camera',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='backend.Camera'),
        ),
        migrations.AddField(
            model_name='clip',
            name='folder',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.Folder'),
        ),
        migrations.AddConstraint(
            model_name='camera',
            constraint=models.UniqueConstraint(fields=('latitude', 'longitude'), name='position constraint'),
        ),
        migrations.AddConstraint(
            model_name='folder',
            constraint=models.UniqueConstraint(fields=('parent', 'name'), name='parent and name constraint'),
        ),
        migrations.AddConstraint(
            model_name='folder',
            constraint=models.UniqueConstraint(fields=('path', 'name'), name='path and name constraint'),
        ),
        migrations.AddConstraint(
            model_name='clip',
            constraint=models.UniqueConstraint(fields=('folder', 'name', 'video_format'), name='path constraint'),
        ),
    ]
