# Generated by Django 3.0.3 on 2020-03-27 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='clip',
            name='path constraint',
        ),
        migrations.RemoveConstraint(
            model_name='folder',
            name='parent and name constraint',
        ),
        migrations.RemoveConstraint(
            model_name='folder',
            name='path and name constraint',
        ),
        migrations.AddConstraint(
            model_name='clip',
            constraint=models.UniqueConstraint(fields=('folder', 'name', 'video_format'), name='clip path constraint'),
        ),
        migrations.AddConstraint(
            model_name='folder',
            constraint=models.UniqueConstraint(fields=('path', 'name'), name='folder path constraint'),
        ),
    ]
