# Generated by Django 3.0.3 on 2020-03-11 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_auto_20200311_1138'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='clip',
            constraint=models.UniqueConstraint(fields=('folder', 'name'), name='folder and name constraint'),
        ),
    ]
