# Generated by Django 3.0.3 on 2020-03-31 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_auto_20200327_0939'),
    ]

    operations = [
        migrations.AlterField(
            model_name='folder',
            name='path',
            field=models.CharField(default='/home/user/', max_length=200),
            preserve_default=False,
        ),
    ]
