# Generated by Django 3.0.3 on 2020-03-15 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0003_auto_20200311_1638'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='clip',
            name='folder and name constraint',
        ),
        migrations.AddConstraint(
            model_name='clip',
            constraint=models.UniqueConstraint(fields=('folder', 'name', 'video_format'), name='path constraint'),
        ),
    ]
