# Generated by Django 3.0.3 on 2020-04-06 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0003_auto_20200331_1008'),
    ]

    operations = [
        migrations.AddField(
            model_name='clip',
            name='height',
            field=models.IntegerField(default=256),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='clip',
            name='width',
            field=models.IntegerField(default=240),
            preserve_default=False,
        ),
    ]
