# Generated by Django 3.0.3 on 2020-04-07 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0004_auto_20200406_1401'),
    ]

    operations = [
        migrations.AddField(
            model_name='clip',
            name='frame_rate',
            field=models.IntegerField(default=42),
            preserve_default=False,
        ),
    ]
