# Generated by Django 3.0.3 on 2020-04-07 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0005_clip_frame_rate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clip',
            name='frame_rate',
            field=models.FloatField(),
        ),
    ]
