# Generated by Django 3.0.3 on 2020-04-07 13:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0005_auto_20200407_1407'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='filter',
            name='name',
        ),
    ]
