# Generated by Django 3.0.3 on 2020-03-16 20:49

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0005_auto_20200315_1736'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filter',
            name='end_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='end time'),
        ),
        migrations.AlterField(
            model_name='filter',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(-90.0), django.core.validators.MaxValueValidator(90.0)], verbose_name='latitude (degrees)'),
        ),
        migrations.AlterField(
            model_name='filter',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=11, null=True, validators=[django.core.validators.MinValueValidator(-180.0), django.core.validators.MaxValueValidator(180.0)], verbose_name='longitude (degrees)'),
        ),
        migrations.AlterField(
            model_name='filter',
            name='radius',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Radius (m)'),
        ),
        migrations.AlterField(
            model_name='filter',
            name='start_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='start time'),
        ),
    ]
