# Generated by Django 3.0.3 on 2020-04-07 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0007_auto_20200407_1556'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='filter',
            name='matching_cameras',
        ),
        migrations.AlterField(
            model_name='filter',
            name='min_frame_rate',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Minimum frame Rate'),
        ),
        migrations.AlterField(
            model_name='filter',
            name='min_height',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Minimum Height'),
        ),
        migrations.AlterField(
            model_name='filter',
            name='min_width',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Minimum width'),
        ),
    ]
