# Generated by Django 3.0.3 on 2020-04-08 10:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0006_auto_20200407_1405'),
        ('backend', '0008_auto_20200407_1623'),
    ]

    operations = [
    ]
