# Generated by Django 3.0.3 on 2020-04-12 17:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0010_auto_20200408_2203'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='objectdetection',
            name='camera',
        ),
        migrations.AddField(
            model_name='objectdetection',
            name='clip',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='backend.Clip'),
            preserve_default=False,
        ),
    ]
