# Generated by Django 3.0.3 on 2020-04-12 10:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0011_auto_20200412_1157'),
    ]

    operations = [
        migrations.AddField(
            model_name='clip',
            name='resolution',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='backend.Resolution'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='filter',
            name='blacklisted_resolutions',
            field=models.ManyToManyField(to='backend.Resolution'),
        ),
    ]
