# Generated by Django 3.0.3 on 2020-04-12 18:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0012_auto_20200412_1216'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='filter',
            name='min_height',
        ),
        migrations.RemoveField(
            model_name='filter',
            name='min_width',
        ),
    ]
