# Generated by Django 3.0.3 on 2020-04-12 19:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0013_auto_20200412_2032'),
        ('backend', '0011_auto_20200412_1933'),
    ]

    operations = [
    ]
