# Generated by Django 3.0.3 on 2020-04-14 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0015_progress'),
    ]

    operations = [
        migrations.AddField(
            model_name='clip',
            name='duplicates',
            field=models.ManyToManyField(related_name='_clip_duplicates_+', to='backend.Clip'),
        ),
    ]
