# Generated by Django 3.0.3 on 2020-04-14 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0016_clip_duplicates'),
    ]

    operations = [
        migrations.AddField(
            model_name='clip',
            name='overlap',
            field=models.ManyToManyField(related_name='_clip_overlap_+', to='backend.Clip'),
        ),
    ]
