# Generated by Django 3.0.3 on 2020-04-15 13:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('backend', '0017_clip_overlap'),
    ]

    operations = [
        migrations.CreateModel(
            name='Area',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('longitude', models.DecimalField(decimal_places=7, max_digits=10)),
                ('latitude', models.DecimalField(decimal_places=7, max_digits=10)),
                ('radius', models.DecimalField(decimal_places=7, max_digits=10)),
            ],
        ),
    ]
