# Generated by Django 3.0.3 on 2020-04-15 14:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('backend', '0018_area'),
    ]

    operations = [
        migrations.AddField(
            model_name='filter',
            name='areas',
            field=models.ManyToManyField(to='backend.Area'),
        ),
    ]
