# Generated by Django 3.0.3 on 2020-04-22 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0020_auto_20200417_1123'),
    ]

    operations = [
        migrations.AddField(
            model_name='clip',
            name='hash_sum',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
