# Generated by Django 3.0.3 on 2020-04-23 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0021_clip_hash_sum'),
    ]

    operations = [
        migrations.AddField(
            model_name='folder',
            name='is_entry',
            field=models.BooleanField(default=False),
        ),
    ]
