# Generated by Django 3.0.3 on 2020-04-25 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0023_camera_name'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='camera',
            name='position constraint',
        ),
        migrations.AddConstraint(
            model_name='camera',
            constraint=models.UniqueConstraint(fields=('name', 'latitude', 'longitude'), name='name and position constraint'),
        ),
    ]
