# Generated by Django 3.0.3 on 2020-04-28 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0024_auto_20200425_1145'),
    ]

    operations = [
        migrations.AddField(
            model_name='clip',
            name='playable',
            field=models.BooleanField(default=False),
        ),
    ]
