# Generated by Django 3.0.3 on 2020-04-29 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0025_clip_playable'),
    ]

    operations = [
        migrations.AlterField(
            model_name='area',
            name='radius',
            field=models.PositiveIntegerField(),
        ),
    ]
