# Generated by Django 3.0.3 on 2020-04-29 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0026_auto_20200429_1417'),
    ]

    operations = [
        migrations.AlterField(
            model_name='area',
            name='radius',
            field=models.DecimalField(decimal_places=7, max_digits=10),
        ),
    ]
