# Generated by Django 3.0.3 on 2020-04-29 13:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0026_auto_20200429_1553'),
        ('backend', '0027_auto_20200429_1525'),
    ]

    operations = [
    ]
